In [1]:
# NumPy - Array From Existing Data
import numpy as np
x = [1, 2, 3, 4]
a = np.asarray(x)
a

array([1, 2, 3, 4])

In [2]:
tup = (1, 2, 3, 4 , 5)
type(tup)

tuple

In [3]:
array = np.asarray(tup)
array

array([1, 2, 3, 4, 5])

In [4]:
x = [12, 23, 34, 45, 56, 67, 78]
x = np.asarray(x)
x

array([12, 23, 34, 45, 56, 67, 78])

In [5]:
y = [23, 12, 34, 23, 45, 56, 78]
x = np.asarray(y, dtype = int)
x

array([23, 12, 34, 23, 45, 56, 78])

In [6]:
y = [23, 12, 34, 23, 45, 56, 78]
x = np.asarray(y, dtype = np.float)
x

array([23., 12., 34., 23., 45., 56., 78.])

In [8]:
y = [23, 12, 34, 23, 45, 56, 78]
x = np.asarray(y, dtype = np.float)
x

array([23., 12., 34., 23., 45., 56., 78.])

In [1]:
# convert list to ndarray
import numpy as np
x = [1, 2, 3]
a = np.asarray(x)
print(a)

[1 2 3]


In [13]:
# dtype is set
import numpy as np
x = [1, 2, 3]
a = np.asarray(x, dtype='f4')
a

array([1., 2., 3.], dtype=float32)

In [14]:
dt = np.dtype('i8')
dt

dtype('int64')

In [15]:
# dtype is set
import numpy as np
x = [1, 2, 3]
a = np.asarray(x, dtype=float)
a

array([1., 2., 3.])

In [16]:
# ndarray from tuple
import numpy as np
x = (1, 2, 3)
type(x)

tuple

In [17]:
a = np.asarray(x)
a

array([1, 2, 3])

In [20]:
# ndarray from list of tuples 
import numpy as np
x = [(1, 2, 3), (4, 5, 6)]
print(type(x))
x

<class 'list'>


[(1, 2, 3), (4, 5, 6)]

In [21]:
a = np.asarray(x)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.ndim

2

In [27]:
# demonstrate the use of frombuffer function.
import numpy as np
s = 'Hello World'
a = np.frombuffer(s, dtype = 'S1')
a

AttributeError: 'str' object has no attribute '__buffer__'