In [3]:
#1 numpy.empty
import numpy as np
x = np.empty([3, 2], dtype = int)
x

array([[1920298854, 1634036768],
       [1932358771, 1768843113],
       [1633904998, 1646294126]])

In [4]:
x[0][0] = 2

In [5]:
x

array([[         2, 1634036768],
       [1932358771, 1768843113],
       [1633904998, 1646294126]])

In [6]:
for i in range(3):
    for j in range(2):
        x[i][j] = i+2

In [7]:
x

array([[2, 2],
       [3, 3],
       [4, 4]])

In [3]:
#2. numpy.zeros
import numpy as np
x = np.zeros([3, 2], dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [4]:
array = np.empty(7, dtype = int)
array

array([-958528704,        119,          0,          0,          0,
                0, 1936532091])

In [6]:
x = np.empty(6, dtype = int)
x

array([-925882160,        119,          0,          0,          1,
                0])

In [7]:
y = np.empty([2, 3, 2])
y

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [8]:
y = np.empty([3, 3, 4], dtype = int)

In [9]:
y

array([[[2097217, 7274606, 2949230, 7077986],
        [6488175, 6881387, 6750318, 7536672],
        [6488175, 6619243, 2097268, 7340143]],

       [[7471205, 7602273, 7274601, 2097262],
        [7274595, 7078005, 2097252, 7274606],
        [2097268, 6619234, 6488096, 7143535]],

       [[7078000, 7602277, 6553701, 6881312],
        [7143533, 6553701, 6357097, 6619252],
        [7929964,       0,       0, 7077985]]])

In [10]:
x = np.zeros(5, dtype = int)
x

array([0, 0, 0, 0, 0])

In [11]:
array = np.zeros([3, 4], dtype = int)
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
x = np.empty(5)
x

array([0., 0., 0., 0., 0.])

In [13]:
import numpy as np
x = np.zeros(5, dtype = np.int)
x

array([0, 0, 0, 0, 0])

In [14]:
#3. numpy.ones
import numpy as np
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [15]:
array = np.ones([2, 4])
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array = np.ones([2, 4], dtype = np.int)
array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
array.ndim

2

In [21]:
array.itemsize

4

In [22]:
x = [1, 2, 3, 4, 5]
type(x)

list

In [23]:
x = np.asarray(x)
x

array([1, 2, 3, 4, 5])

In [24]:
type(x)

numpy.ndarray