In [1]:
# using array scaler type
import numpy as np

In [3]:
dataType = np.dtype(np.int32)

In [4]:
dataType

dtype('int32')

In [13]:
# int8, int16, int 32, int64 can be replace by equivalent string 'i1', 'i2', 'i4', and 'i8' etc.
dt = np.dtype('i1')

In [24]:
dt

dtype('int64')

In [25]:
dt = np.dtype('i2')

In [26]:
dt

dtype('int16')

In [27]:
dt = np.dtype('i4')

In [28]:
dt

dtype('int32')

In [29]:
dt = np.dtype("i8")

In [30]:
dt

dtype('int64')

In [31]:
# first create structure
dt = np.dtype([('age', np.int8)])

In [32]:
dt

dtype([('age', 'i1')])

In [34]:
dt = np.dtype([('age', 'i8'), ('Id', 'i4')])

In [35]:
dt

dtype([('age', '<i8'), ('Id', '<i4')])

In [36]:
dt = np.dtype([("age", np.int8)])

In [37]:
dt

dtype([('age', 'i1')])

In [38]:
# now apply it to the ndarray object
dt = np.dtype([("age", np.int8)])

In [39]:
dt

dtype([('age', 'i1')])

In [42]:
a = np.array([(10,), (20,), (30,)], dtype = dt)

In [43]:
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [44]:
dt = np.dtype([('age', np.int8)])

In [45]:
dt

dtype([('age', 'i1')])

In [46]:
a = np.array([(10,), (20,), (30,)], dtype = dt)

In [47]:
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [58]:
print(a['age'])

[19 19 19]


In [59]:
import numpy as np

In [60]:
student = np.dtype([("name", 'S20'), ('age', 'i1'), ("marks", 'f4')])

In [61]:
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [62]:
a = np.array([("Lalit", 19, 99), ("Suraj", 19, 97), ("Sunil", 19, 90)], dtype = student)

In [63]:
a

array([(b'Lalit', 19, 99.), (b'Suraj', 19, 97.), (b'Sunil', 19, 90.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [64]:
a['name']

array([b'Lalit', b'Suraj', b'Sunil'], dtype='|S20')

In [65]:
a['age']

array([19, 19, 19], dtype=int8)

In [66]:
a['marks']

array([99., 97., 90.], dtype=float32)

In [71]:
info = np.dtype([("Name", 'S30'), ("FName", 'S20'), ("MName", 'S20')])

In [72]:
info

dtype([('Name', 'S30'), ('FName', 'S20'), ('MName', 'S20')])

In [73]:
array = np.array([("Lalit Siraswa", "Shivdan Siraswa", "Manju Devi")], dtype = info)

In [74]:
array

array([(b'Lalit Siraswa', b'Shivdan Siraswa', b'Manju Devi')],
      dtype=[('Name', 'S30'), ('FName', 'S20'), ('MName', 'S20')])

In [78]:
dt = np.dtype([("Name", 'S30'), ("RollNo", np.int32), ("Marks", np.float32)])

In [79]:
dt

dtype([('Name', 'S30'), ('RollNo', '<i4'), ('Marks', '<f4')])

In [80]:
array = np.array([("ABC", 19, 98), ("ACD", 32, 89), ("XYZ", 67, 78), ("DFR", 45, 79)])

In [81]:
array

array([['ABC', '19', '98'],
       ['ACD', '32', '89'],
       ['XYZ', '67', '78'],
       ['DFR', '45', '79']], dtype='<U3')

In [82]:
type(array)

numpy.ndarray

In [83]:
array = np.array([("ABC", 19, 98), ("ACD", 32, 89), ("XYZ", 67, 78), ("DFR", 45, 79)], dtype = dt)

In [84]:
array

array([(b'ABC', 19, 98.), (b'ACD', 32, 89.), (b'XYZ', 67, 78.),
       (b'DFR', 45, 79.)],
      dtype=[('Name', 'S30'), ('RollNo', '<i4'), ('Marks', '<f4')])

In [86]:
# Everything is object in Python
id(array)

410992984752

In [3]:
import numpy as np
dt = np.dtype([("Name", 'S30'), ("Age", np.int32), ("Marks", np.float32)])

In [4]:
print(dt)

[('Name', 'S30'), ('Age', '<i4'), ('Marks', '<f4')]


In [5]:
Array = np.array([("A", 12, 89), ("B", 15, 90), ("C", 16, 78)])

In [6]:
Array

array([['A', '12', '89'],
       ['B', '15', '90'],
       ['C', '16', '78']], dtype='<U2')

In [7]:
Array = np.array([("A", 12, 89), ("B", 15, 90), ("C", 16, 78)], dtype = dt)

In [8]:
Array

array([(b'A', 12, 89.), (b'B', 15, 90.), (b'C', 16, 78.)],
      dtype=[('Name', 'S30'), ('Age', '<i4'), ('Marks', '<f4')])

In [11]:
Array['Name']

array([b'A', b'B', b'C'], dtype='|S30')

In [12]:
Array['Age']

array([12, 15, 16])

In [13]:
Array['Marks']

array([89., 90., 78.], dtype=float32)