In [2]:
import numpy as np

In [3]:
x = [x for x in range(11) if x % 2 == 0]
x

[0, 2, 4, 6, 8, 10]

In [4]:
y = ([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12])
y

([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12])

In [5]:
np.array(x)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.array(y)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
x = [1, 2, 3]
y = [4, 5, 6]

In [13]:
x + y

[1, 2, 3, 4, 5, 6]

In [14]:
x * 2

[1, 2, 3, 1, 2, 3]

In [15]:
np.zeros(5) + 2

array([2., 2., 2., 2., 2.])

In [16]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
type(np.eye(3))

numpy.ndarray

In [19]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(4, 15)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(3)

array([0, 1, 2])

In [26]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.reshape(x, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.arange(50).reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
np.linspace(0, 500, 30)

array([  0.        ,  17.24137931,  34.48275862,  51.72413793,
        68.96551724,  86.20689655, 103.44827586, 120.68965517,
       137.93103448, 155.17241379, 172.4137931 , 189.65517241,
       206.89655172, 224.13793103, 241.37931034, 258.62068966,
       275.86206897, 293.10344828, 310.34482759, 327.5862069 ,
       344.82758621, 362.06896552, 379.31034483, 396.55172414,
       413.79310345, 431.03448276, 448.27586207, 465.51724138,
       482.75862069, 500.        ])

In [45]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [47]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [50]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [51]:
x = [i for i in range(10)] 

In [52]:
np.max(x)

9

In [53]:
np.min(x)

0

In [56]:
x = np.array(x)

In [58]:
x.max()

9

In [59]:
x.min()

0

In [66]:
x = [i for i in range(110) if i % 10 == 0 and i != 0]

In [67]:
x

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [69]:
x = np.array(x)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [74]:
random = np.random.rand(5)
random

array([0.53176327, 0.45621421, 0.22963908, 0.9921634 , 0.7983216 ])

In [75]:
np.random.randn(10)

array([ 0.34124489,  2.25057517,  1.09560589, -0.71466315, -1.84075639,
        1.5938792 ,  0.63659909,  0.29789535,  0.71532181, -1.38464227])

In [77]:
np.random.randint(10)

5

In [78]:
np.random.randint(100)

35

In [79]:
x = [i for i in range(110) if i % 10 == 0 and i != 0]
x

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [81]:
x = np.array(x)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [84]:
x.argmax()

9

In [85]:
x.argmin()

0

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])