In [14]:
import numpy as np

In [15]:
array = np.array([2, 4, 6, 8], order='F')

In [16]:
array

array([2, 4, 6, 8])

In [20]:
a = np.array([[1, 2], [3, 4]])

In [23]:
a

array([[1, 2],
       [3, 4]])

In [28]:
# minimum dimension
a = np.array([1, 2, 3, 4, 5], ndmin = 3)

In [29]:
a

array([[[1, 2, 3, 4, 5]]])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ndmin = 3)

In [33]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
# dtype = complex
a = np.array([1, 2, 3], dtype = complex)

In [35]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])