In [2]:
import numpy as np

In [3]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(x[0 : , 0], "\n")
print(x[0 : , 0 : 1])

[1 3 5] 

[[1]
 [3]
 [5]]


In [5]:
y = x[[0, 1, 2], [0, 1, 0]]
y

array([1, 4, 5])

In [6]:
print(x[[0, 1, 2], [1, 0, 1]])

[2 3 6]


In [7]:
print(x[[0, 1, 2], [1, 1, 0]])

[2 4 5]


In [8]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print("Our array is : ")
print(x, "\n")
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
print(rows, "\n\n", cols)

Our array is : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[0 0]
 [3 3]] 

 [[0 2]
 [0 2]]


In [11]:
print(x[[[0, 0], [3, 3]], [[0, 2], [0, 2]]])

[[ 0  2]
 [ 9 11]]


In [25]:
print(x[[0, 1, 2, 3], [0, 2, 0, 2]])

[ 0  5  6 11]


In [27]:
print(x[[[0, 0], [1, 1], [2, 2], [3, 3]], [[0, 2], [0, 2], [0, 2], [0, 2]]])

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [32]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [33]:
print(a[[0, 1, 2, 3, 4], [2, 1, 0, 1, 2]])

[ 2  4  6 10 14]


In [34]:
print(a[[[0, 0], [4, 4]], [[0, 2], [0, 2]]])

[[ 0  2]
 [12 14]]


In [36]:
print(a[[0, 2, 4], [0, 1, 2]])

[ 0  7 14]


In [38]:
print(a[[[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]], [[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [40]:
print(a[[0, 2, 4], [2, 1, 0]])

[ 2  7 12]


In [41]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
print(a[1 : 4, 1 : 3])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [45]:
print(a[ 0 : , 1])
print(a[0 :, 1 : 2])

[ 1  4  7 10]
[[ 1]
 [ 4]
 [ 7]
 [10]]


In [47]:
print(a[1 : 4, [1, 2]])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [51]:
print(a[0 : , 2])

[ 2  5  8 11]


In [52]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
print(a[[0, 1, 2, 3], [0, 1, 1, 0]])

[0 4 7 9]


In [56]:
print(a[[[0, 0], [1, 1], [2, 2], [3, 3]], [[0, 2], [1, 2], [1, 2], [0, 2]]])

[[ 0  2]
 [ 4  5]
 [ 7  8]
 [ 9 11]]


In [58]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
a > 7

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [61]:
print(a[a > 7])

[ 8  9 10 11]


In [65]:
print((a > 4) & (a < 9))
print("\n", a[(a > 4) & (a < 9)])

[[False False False]
 [False False  True]
 [ True  True  True]
 [False False False]]

 [5 6 7 8]


In [12]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print("Our array is : ")
print(x, "\n")
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
print(rows, "\n\n", cols)

Our array is : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[0 0]
 [3 3]] 

 [[0 2]
 [0 2]]


In [16]:
x[[1, 2], [1, 1]]

array([4, 7])

In [17]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [19]:
a[0 : , [0, 2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11],
       [12, 14]])