In [6]:
# numpy.arange
import numpy as np
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [7]:
x = np.arange(start=5, stop=20, step=2)
print(x) 

[ 5  7  9 11 13 15 17 19]


In [11]:
# float
x = np.arange(10, dtype=np.float64)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [14]:
x = np.arange(start=10, stop=30, step=2, dtype=np.float64)
print(x)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


In [15]:
# start and stop parameters set
import numpy as np
x = np.arange(10, 20, 2, dtype=np.float)
print(x)

[10. 12. 14. 16. 18.]
