In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)
s = slice(2, 7, 2)
print(s)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]


In [3]:
a = np.arange(10)
print(a)
print("a[2:7:2] : ", a[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
a[2:7:2] :  [2 4 6]


In [4]:
a = np.array([x for x in range(110) if x % 10 == 0 and x!= 0])
print(a)
print(a[0], a[1])
print(a[8], a[9])

[ 10  20  30  40  50  60  70  80  90 100]
10 20
90 100


In [5]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
b = a[4]
b

5

In [7]:
a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [8]:
a = range(10)
a

range(0, 10)

In [9]:
it = iter(a)
x = np.fromiter(it, int)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = range(10)
print(a)

range(0, 10)


In [11]:
a[5]

5

In [12]:
a = np.arange(10)
print(a[2 : 5])

[2 3 4]


In [13]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [14]:
print(a[0])
print(a[1])
print(a[2])

[1 2 3]
[3 4 5]
[4 5 6]


In [15]:
a = np.array((1, 2, 3))
a[0]

1

In [16]:
a = [x for x in range(31)]
a = np.array(a)
print(a)
print(a[-10 : -1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[21 22 23 24 25 26 27 28 29]


In [17]:
a = np.arange(31)

In [18]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [19]:
x = a[0 : 11] = 49
type(x)

int

In [20]:
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
x = a[0 : 6] = 89
print(x)
print(a)

89
[89 89 89 89 89 89  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
y = a[5 : 16] = 99
print(y)
print(a)

99
[ 0  1  2  3  4 99 99 99 99 99 99 99 99 99 99 99 16 17 18 19 20]


In [24]:
y = a.copy()
print(a)
print(y)

[ 0  1  2  3  4 99 99 99 99 99 99 99 99 99 99 99 16 17 18 19 20]
[ 0  1  2  3  4 99 99 99 99 99 99 99 99 99 99 99 16 17 18 19 20]


In [25]:
a = 
print(a.shape)
a.shape = (5, 5)
print(a.shape)
print(a)

SyntaxError: invalid syntax (<ipython-input-25-83fba3b94cde>, line 1)

In [26]:
a = np.array(range(25))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
print(type(range(34)))

<class 'range'>


In [28]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
for i in range(5):
    for j in range(5):
        print(a[i][j], end = " ,  ")
        
print("\n",a[2][2])

0 ,  1 ,  2 ,  3 ,  4 ,  5 ,  6 ,  7 ,  8 ,  9 ,  10 ,  11 ,  12 ,  13 ,  14 ,  15 ,  16 ,  17 ,  18 ,  19 ,  20 ,  21 ,  22 ,  23 ,  24 ,  
 12


In [31]:
a = np.array([1, 2, 3, 4, 5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

In [32]:
a = np.arange(20).reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
a[4][2]

22

In [35]:
a[2, 2]

12

In [36]:
a[4, 4]

24

In [37]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
a[0:2, 1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [39]:
a[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [40]:
a[:, 2:3]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [41]:
a[:, 0]

array([ 0,  5, 10, 15, 20])

In [42]:
a[:, 0:1]

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [43]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
print(a > 10)
print(a[a > 10])

[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]
[11 12 13 14 15 16 17 18 19 20]


In [46]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
print(a[0][0], a[1][1], a[2][2], a[3][3], a[4][4])

0 6 12 18 24


In [48]:
print(a[0, 0], a[1, 1], a[2, 2], a[3, 3], a[4, 4])

0 6 12 18 24


In [51]:
print(a[0 : , 0 : 1])
print(a[0 : , 0])

[[ 0]
 [ 5]
 [10]
 [15]
 [20]]
[ 0  5 10 15 20]


In [53]:
print(a[0 : , 0 : 1], a[0 : , 1 : 2], a[0 : , 2 : 3], a[0 : , 3 : 4], a[0 : , 4 : 5])

[[ 0]
 [ 5]
 [10]
 [15]
 [20]] [[ 1]
 [ 6]
 [11]
 [16]
 [21]] [[ 2]
 [ 7]
 [12]
 [17]
 [22]] [[ 3]
 [ 8]
 [13]
 [18]
 [23]] [[ 4]
 [ 9]
 [14]
 [19]
 [24]]


In [56]:
print(a)
print(a[0 : , 0])
print(a[0 : , 1])
print(a[0 : , 2])
print(a[0 : , 3])
print(a[0 : , 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  5 10 15 20]
[ 1  6 11 16 21]
[ 2  7 12 17 22]
[ 3  8 13 18 23]
[ 4  9 14 19 24]


In [57]:
a[0]

array([0, 1, 2, 3, 4])

In [59]:
a > 15

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [62]:
a[a > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
a < 5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [64]:
a[a < 5]

array([0, 1, 2, 3, 4])

In [68]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [69]:
a[a % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [71]:
a[a % 5 == 0]

array([ 0,  5, 10, 15, 20])

In [72]:
a[a % 6 == 0]

array([ 0,  6, 12, 18, 24])