In [1]:
import numpy as np

In [2]:
a = np.arange(0, 60, 5)
print(a)
print(a.shape) 
a.shape = (3, 4) # a.reshape(3, 4)
print(a.shape)
print("Original Array Is : ")
print(a, "\n")

print("Modified Array Is : ")
for x in np.nditer(a):
    print (x, end = " ,  ")

[ 0  5 10 15 20 25 30 35 40 45 50 55]
(12,)
(3, 4)
Original Array Is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Modified Array Is : 
0 ,  5 ,  10 ,  15 ,  20 ,  25 ,  30 ,  35 ,  40 ,  45 ,  50 ,  55 ,  

In [3]:
x = np.array([10, 20, 30, 40, 50, 60, 70 , 80, 90, 100])
for i in np.nditer(x):
    print(i, end=" ,  ")

10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [4]:
x.reshape(5, 2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [5]:
x.ndim

1

In [6]:
x = np.array([i for i in range(110) if i % 10 == 0 and i != 0], ndmin = 3)
print(x)
print(x.ndim)
for i in x:
    print(i, end = " ,  ")
print("\n")
for i in np.nditer(x):
    print(i, end = " ,  ")

[[[ 10  20  30  40  50  60  70  80  90 100]]]
3
[[ 10  20  30  40  50  60  70  80  90 100]] ,  

10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [7]:
a = np.arange(0, 60, 5)
print(a)
print(a.shape)
a = a.reshape(3, 4)
print("Original Array Is : ")
print(a, "\n")
print("Transpose of the original Array is :")
b = a.T
print(b)
print("\n")

print("Modified Array Is : ")
for i in np.nditer(b):
    print(i, end = " ,  ")
print("\n")

[ 0  5 10 15 20 25 30 35 40 45 50 55]
(12,)
Original Array Is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Transpose of the original Array is :
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified Array Is : 
0 ,  5 ,  10 ,  15 ,  20 ,  25 ,  30 ,  35 ,  40 ,  45 ,  50 ,  55 ,  



In [8]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
for i in np.nditer(x):
    print(i, end = " ,  ")

1 ,  2 ,  3 ,  4 ,  5 ,  6 ,  7 ,  

In [9]:
x = np.arange(1, 26).reshape(5, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
for a in np.nditer(x):
    print(a, end = " ,  ")

1 ,  2 ,  3 ,  4 ,  5 ,  6 ,  7 ,  8 ,  9 ,  10 ,  11 ,  12 ,  13 ,  14 ,  15 ,  16 ,  17 ,  18 ,  19 ,  20 ,  21 ,  22 ,  23 ,  24 ,  25 ,  

In [11]:
x = np.array([i for i in range(201) if i % 10 == 0 and i != 0])
print(x)
print(len(x))

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]
20


In [12]:
x.shape = (5, 4)
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [13]:
x = x.T
print(x)

[[ 10  50  90 130 170]
 [ 20  60 100 140 180]
 [ 30  70 110 150 190]
 [ 40  80 120 160 200]]


In [14]:
a = np.arange(0, 60, 5)
print(len(a), "\n")
a = a.reshape(4, 3)
print(a)

12 

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]


In [15]:
print("Original Array Is : ")
print(a, "\n")
print("Transpose of the original array is : ")
b = a.T
print(b, "\n")

Original Array Is : 
[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]] 

Transpose of the original array is : 
[[ 0 15 30 45]
 [ 5 20 35 50]
 [10 25 40 55]] 



In [16]:
x = np.array([2, 4, 6, 8, 10], dtype = "i8")
x

array([ 2,  4,  6,  8, 10], dtype=int64)

In [17]:
x = np.array([2, 4, 6, 8, 10], ndmin = 3)
x

array([[[ 2,  4,  6,  8, 10]]])

In [18]:
a = np.arange(0, 60, 5)
print(len(a), "\n")
a = a.reshape(4, 3)
print(a)

12 

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]


In [19]:
print("Sorted in C-style order : ")
c = b.copy(order = "C")
print(c)
for x in np.nditer(c):
    print(x, end = " ,  ")
    
print("\n\nSorted in F-style order : ")
c = b.copy(order = "F")
print(c)
for i in np.nditer(c):
    print(i, end = " ,  ")

Sorted in C-style order : 
[[ 0 15 30 45]
 [ 5 20 35 50]
 [10 25 40 55]]
0 ,  15 ,  30 ,  45 ,  5 ,  20 ,  35 ,  50 ,  10 ,  25 ,  40 ,  55 ,  

Sorted in F-style order : 
[[ 0 15 30 45]
 [ 5 20 35 50]
 [10 25 40 55]]
0 ,  5 ,  10 ,  15 ,  20 ,  25 ,  30 ,  35 ,  40 ,  45 ,  50 ,  55 ,  

In [20]:
x = np.arange(10, 201, 10).reshape(5, 4)
print(x)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]
 [170 180 190 200]]


In [21]:
arr = np.array(x, order = "C")
print(arr)
for i in np.nditer(arr):
    print(i, end = " ,  ")

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]
 [170 180 190 200]]
10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  110 ,  120 ,  130 ,  140 ,  150 ,  160 ,  170 ,  180 ,  190 ,  200 ,  

In [22]:
arr = np.array(x, order = "F")
print(arr)
for i in np.nditer(arr):
    print(i, end = " ,  ")

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]
 [170 180 190 200]]
10 ,  50 ,  90 ,  130 ,  170 ,  20 ,  60 ,  100 ,  140 ,  180 ,  30 ,  70 ,  110 ,  150 ,  190 ,  40 ,  80 ,  120 ,  160 ,  200 ,  

In [23]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("Original array is : ")
print(a, "\n")

print("Sorted in C-style order : ")
for x in np.nditer(a, order = "C"):
    print(x, end = " ,  ")
print("\n")

print("Sorted in F-style order : ")
for x in np.nditer(a, order = "F"):
    print(x, end = " ,  ")

Original array is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Sorted in C-style order : 
0 ,  5 ,  10 ,  15 ,  20 ,  25 ,  30 ,  35 ,  40 ,  45 ,  50 ,  55 ,  

Sorted in F-style order : 
0 ,  20 ,  40 ,  5 ,  25 ,  45 ,  10 ,  30 ,  50 ,  15 ,  35 ,  55 ,  

In [24]:
x = np.array([1, 2, 3, 4, 5], ndmin = 3)
x.ndim

3

In [25]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("Original array is : ")
print(a, "\n")

for x in np.nditer(a, op_flags = ["readwrite"]):
    x[...] = 2 * x
print("Modified array is : ")
print(a)

Original array is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Modified array is : 
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [26]:
a = np.arange(0, 60, 5)
a.shape = (3, 4)
print(a)
for i in np.nditer(a):
    print(i[...], end = " ,  ")
#     print(i, end = " , ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 ,  5 ,  10 ,  15 ,  20 ,  25 ,  30 ,  35 ,  40 ,  45 ,  50 ,  55 ,  

In [27]:
print(i[...])

55


In [28]:
x = np.array([i for i in range(110) if i % 10 == 0 and i != 0])
print(x)
for i in np.nditer(x):
    print(i[...], end = " ,  ")

[ 10  20  30  40  50  60  70  80  90 100]
10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [29]:
for i in np.nditer(x, op_flags = ["readonly"]):
    print(i[...], end = " ,  ")

10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [30]:
for i in np.nditer(x, op_flags = ["writeonly"]):
#     print(i, end = " ,  ")
    print(i[...], end = " ,  ")

10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [31]:
for a in np.nditer(x, op_flags = ["readonly"]):
    a[...] = 2 * a

ValueError: assignment destination is read-only

In [32]:
for a in np.nditer(x, op_flags = ["writeonly"]):
    print(a[...], end = " ,  ")

10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  

In [33]:
for a in np.nditer(x, op_flags = ["readwrite"]):
    a[...] = a * 2

In [34]:
print(x)

[ 20  40  60  80 100 120 140 160 180 200]


In [52]:
x = np.arange(0, 200, 10)
len(x)
x.shape = (5, 4)
print(x)
for y in np.nditer(x, op_flags = ["readwrite"]):
    print(y[...], end = " ,  ")
    y[...] = y + 3
print("\n\n",x)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]
 [160 170 180 190]]
0 ,  10 ,  20 ,  30 ,  40 ,  50 ,  60 ,  70 ,  80 ,  90 ,  100 ,  110 ,  120 ,  130 ,  140 ,  150 ,  160 ,  170 ,  180 ,  190 ,  

 [[  3  13  23  33]
 [ 43  53  63  73]
 [ 83  93 103 113]
 [123 133 143 153]
 [163 173 183 193]]


In [63]:
a = np.arange(0, 60, 5)
a.shape = (3, 4)
print("Original array is : ")
print(a, "\n")

print("Modified array is : ")
for x in np.nditer(a, flags = ["external_loop"], order = "F"):
    print(x, end = " ,  ")
print("\n\n")

for x in np.nditer(a, flags = ["c_index"], order = "F"):
    print(x, end = " ,  ")
print("\n\n")



Original array is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Modified array is : 
[ 0 20 40] ,  [ 5 25 45] ,  [10 30 50] ,  [15 35 55] ,  


0 ,  20 ,  40 ,  5 ,  25 ,  45 ,  10 ,  30 ,  50 ,  15 ,  35 ,  55 ,  

In [69]:
a = np.arange(0, 60, 5)
a.shape = (3, 4)
print("First array is : ")
print(a, "\n")

print("Second array is : ")
b = np.array([1, 2, 3, 4], dtype = int)
print(b, "\n")

print("Modifies array is : ")
for x, y in np.nditer([a, b]):
    print("%d : %d" %(x, y), end = " ,  ")
#     print(x, y, end = " ,  ")

First array is : 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

Second array is : 
[1 2 3 4] 

Modifies array is : 
0 : 1 ,  5 : 2 ,  10 : 3 ,  15 : 4 ,  20 : 1 ,  25 : 2 ,  30 : 3 ,  35 : 4 ,  40 : 1 ,  45 : 2 ,  50 : 3 ,  55 : 4 ,  

In [88]:
a = np.arange(0, 120, 10)
a = a.reshape(4, 3)
print("Fisrt array is : ")
print(a, "\n")

print("Second array is : ")
b = np.array([2, 4, 6])
print(b, "\n")

print("Modified array is : ")
for i, j in np.nditer((a, b)):
    print("%d : %d" %(i, j), end = ", ")

Fisrt array is : 
[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]] 

Second array is : 
[2 4 6] 

Modified array is : 
0 : 2, 10 : 4, 20 : 6, 30 : 2, 40 : 4, 50 : 6, 60 : 2, 70 : 4, 80 : 6, 90 : 2, 100 : 4, 110 : 6, 