In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [3]:
print(a + b)
print(a - b)

[11 22 33 44]
[ -9 -18 -27 -36]


In [8]:
a = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
print("First array")
print(a, "\n")

print("Second array")
print(b, "\n")

print("First Array + Second Array")
print(a + b)

First array
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]] 

Second array
[1. 2. 3.] 

First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [18]:
a = np.arange(0, 60, 5)
a.shape = (4, 3)
b = np.array([2, 4, 6])
print("Shape of a array is  : ", a.shape)
print("Shape of b array is  : ", b.shape)

print("First Array : ")
print(a, "\n")

print("Second Array : ")
print(b, "\n")

print(a + b)

Shape of a array is  :  (4, 3)
Shape of b array is  :  (3,)
First Array : 
[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]] 

Second Array : 
[2 4 6] 

[[ 2  9 16]
 [17 24 31]
 [32 39 46]
 [47 54 61]]
