In [3]:
import numpy as np

In [4]:
#1. ndarray.shape
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
# this also use to resize the array
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

(2, 3)

In [8]:
a.shape = (3, 2)

In [9]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
array = np.array([[1, 2, 3], [5, 6, 7]])

In [11]:
array

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
array.shape

(2, 3)

In [13]:
a.shape = (3, 2)

In [14]:
# numpy also provide a reshape function to resize an array
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a.shape

(2, 3)

In [18]:
a.shape = (3, 2)

In [19]:
a.shape

(3, 2)

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
b = a.reshape(2, 3)

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#2. ndarray.ndim
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [33]:
a[0]

0

In [35]:
a[22]

22

In [36]:
a.ndim

1

In [37]:
a.shape = (2, 4, 3)

In [38]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [40]:
a.shape = (1, 24)

In [41]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
a = np.arange(24)

In [43]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
a.ndim

1

In [45]:
b = a.reshape(2, 4, 3)

In [46]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [47]:
b.ndim

3

In [48]:
a = np.array([1, 2, 3])

In [49]:
a.ndim

1

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [51]:
a.ndim

2

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [56]:
a.ndim

2

In [67]:
#3. numpy.itemsize
import numpy as np
x = np.array([1, 2, 3, 4, 5], dtype = np.int16)
x

array([1, 2, 3, 4, 5], dtype=int16)

In [68]:
x.itemsize

2

In [69]:
names = np.array(["ABC", "DEFG", "HIJKLM"], dtype = 'S10')

In [70]:
names.itemsize

10

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5], dtype = np.int16)

In [5]:
x

array([1, 2, 3, 4, 5], dtype=int16)

In [6]:
print(x.itemsize)

2


In [7]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6], dtype = np.float32)

In [8]:
x

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [9]:
print(x.itemsize)

4
