In [8]:
import numpy as np

In [9]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
y = np.arange(11, 21)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
z = x + y
z

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
z = x - y
z

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [15]:
x * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
x + y

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [17]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [18]:
x * y

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [19]:
x / y

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [20]:
x % y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [21]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [22]:
np.cos(y)

array([ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206])

In [23]:
x.max()

10

In [24]:
y.max()

20

In [27]:
print(np.max(x))
print(np.max(y))
print(np.min(x))
print(np.min(y))
print(x.min())
print(y.min())

10
20
1
11
1
11


In [31]:
x = np.arange(1, 21).reshape(5, 4)
y = np.arange(21, 41).reshape(5, 4)
print(x, "\n")
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]


In [33]:
z = x + y
print(z)

[[22 24 26 28]
 [30 32 34 36]
 [38 40 42 44]
 [46 48 50 52]
 [54 56 58 60]]


In [34]:
x * y

array([[ 21,  44,  69,  96],
       [125, 156, 189, 224],
       [261, 300, 341, 384],
       [429, 476, 525, 576],
       [629, 684, 741, 800]])

In [37]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20).reshape(5, 4)
print(x, "\n")
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [44]:
x = np.full((3, 3), True)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
np.full((2, 2), False)

array([[False, False],
       [False, False]])

In [57]:
a = np.array([1, 1, 2, 3, 4, 5, 6])
b = np.array([0, 2, 1, 3, 4, 8, 9])
np.intersect1d(a, b)

array([1, 2, 3, 4])