In [6]:
import numpy as np

In [140]:
a = np.array([i for i in range(110) if i % 10 == 0 and i != 0], ndmin = 3, dtype = "str")
a

array([[['10', '20', '30', '40', '50', '60', '70', '80', '90', '100']]],
      dtype='<U3')

In [141]:
a[0][0][0]

'10'

In [142]:
a[0][0][9]

'100'

In [143]:
dt = np.dtype(np.int8)
print(dt)
dt = np.dtype(np.int16)
print(dt)
dt = np.dtype(np.int32)
print(dt)
dt = np.dtype(np.int64)
print(dt)

int8
int16
int32
int64


In [144]:
dt = np.dtype("i1")
print(dt)
dt = np.dtype("i2")
print(dt)
dt = np.dtype("i4")
print(dt)
dt = np.dtype("i8")
print(dt)

int8
int16
int32
int64


In [145]:
dt = np.dtype([('age', np.int8)])
dt

dtype([('age', 'i1')])

In [146]:
dt = np.dtype([("cn", np.int64), ("Age", "i8")])
dt

dtype([('cn', '<i8'), ('Age', '<i8')])

In [147]:
a = np.array([(3456789785, 19), (4567345654, 20)], dtype = dt)
print(a)

[(3456789785, 19) (4567345654, 20)]


In [148]:
a["cn"]

array([3456789785, 4567345654], dtype=int64)

In [149]:
student = np.dtype([("Name", "S20"), ("Age", "i1"), ("Marks", "f4")])
student

dtype([('Name', 'S20'), ('Age', 'i1'), ('Marks', '<f4')])

In [150]:
type(student)

numpy.dtype

In [151]:
a = np.array([("Lalit", 19, 90), ("Suraj", 20, 92), ("Naveen", 20, 96)], dtype=student)

In [152]:
a

array([(b'Lalit', 19, 90.), (b'Suraj', 20, 92.), (b'Naveen', 20, 96.)],
      dtype=[('Name', 'S20'), ('Age', 'i1'), ('Marks', '<f4')])

In [153]:
print(a["Name"])

[b'Lalit' b'Suraj' b'Naveen']


In [154]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("\n", a.shape)

[[1 2 3]
 [4 5 6]]

 (2, 3)


In [155]:
a.shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [156]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [158]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ndmin=4)
print(a)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [159]:
a.ndim

4

In [160]:
a = np.arange(10)
a.ndim

1

In [161]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [162]:
a.ndim

1

In [164]:
a.shape = (4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [165]:
a.shape

(4, 6)

In [170]:
a.shape = (24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [171]:
b = a.reshape(2, 4, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [183]:

x = np.array([14, 25, 34, 46, 53, 66], dtype = np.int8)
print(x)
print("\n", x.itemsize)

[14 25 34 46 53 66]

 1


In [184]:
x = np.array(["Lalit", "Jyoti", "Krishna", "Manisha"], dtype = "S10")
print(x.itemsize)

10


In [185]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [186]:
type(x[0])

numpy.int32

In [187]:
x = np.array(["1", "2", "3"])
x

array(['1', '2', '3'], dtype='<U1')

In [189]:
print(type(x[0]))

<class 'numpy.str_'>


In [192]:
x = np.empty([3, 2], dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [197]:
x = np.empty([3, 2], dtype = int)
x

array([[168733632,        74],
       [        0,         0],
       [        1,         0]])

In [205]:
x = np.zeros((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [206]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [207]:
x = np.zeros([3, 2], dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [203]:
x = np.zeros((2, 2))
x

array([[0., 0.],
       [0., 0.]])

In [208]:
x = np.empty((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [209]:
x = np.empty([3, 2])
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [210]:
x = np.zeros((3, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [211]:
x = np.zeros([4, 3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [212]:
dt = np.dtype([("x", "i4"), ("y", "i4")])
dt

dtype([('x', '<i4'), ('y', '<i4')])

In [213]:
x = np.zeros((3, 3), dtype = dt)
x

array([[(0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

In [214]:
x = np.zeros((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [215]:
x = np.zeros([3, 2], dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [216]:
x = np.zeros([3, 3], dtype = np.int)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [217]:
x = [1, 2, 3, 4]
a = np.asarray(x)
print(x)

[1, 2, 3, 4]


In [221]:
names = ["Lalit", "Amit", "Suraj", "Vikash", "Shohel"]
x = np.asarray(names)
x

array(['Lalit', 'Amit', 'Suraj', 'Vikash', 'Shohel'], dtype='<U6')

In [222]:
x = [x for x in range(110) if x % 10 == 0 and x != 0]
x

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [225]:
x = np.asarray(x)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [227]:
y = np.asarray(x, dtype = float)
y

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [228]:
x = (2, 4, 6, 8)
a = np.asarray(x)
print(a)

[2 4 6 8]


In [230]:
print(a[0])
print(a[1])
print(a[2])
print(a[3])

2
4
6
8


In [231]:
x = [(1, 2, 3), (4, 5, 6)]
a = np.asarray(x)
print(a)

[[1 2 3]
 [4 5 6]]


In [256]:
x = [(1, 2, 3), (4, 5, 6)]
a = np.asarray(x, dtype = "f")
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [266]:
x = np.array([1, 2, 3, 4], dtype = "f2")
x

array([1., 2., 3., 4.], dtype=float16)

In [1]:
list = range(5)
print(list)

range(0, 5)


In [4]:
list = range(5)
print(type(list))
it = iter(list)
print(it)

<class 'range'>


In [7]:
x = np.fromiter(it, dtype = float)
x

array([0., 1., 2., 3., 4.])

In [8]:
list = range(10, 21)
print(list)
print(type(list))

range(10, 21)
<class 'range'>


In [10]:
itr = iter(list)
x = np.fromiter(itr, dtype = int)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [13]:
x = np.arange(5)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0 1 2 3 4]


In [14]:
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [15]:
x = np.arange(1, 20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [17]:
x = np.arange(10, 20, 2)
x

array([10, 12, 14, 16, 18])

In [18]:
np.linspace(1, 2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [19]:
len(np.linspace(10, 20))

50

In [21]:
x = np.linspace(10, 20, 5)
x

array([10. , 12.5, 15. , 17.5, 20. ])